//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PolicyManagerCrudResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolicyManagerCrudResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PolicyManager.Resources.PolicyManagerCrudResources", typeof(PolicyManagerCrudResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of CreateThingAttributeAttribute function.
        /// </summary>
        internal static string CreateThingAttributeEndLog {
            get {
                return ResourceManager.GetString("CreateThingAttributeEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of CreateThingAttribute function.
        /// </summary>
        internal static string CreateThingAttributeStartLog {
            get {
                return ResourceManager.GetString("CreateThingAttributeStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of CreateThingAttribute function.
        /// </summary>
        internal static string CreateThingEndLog {
            get {
                return ResourceManager.GetString("CreateThingEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of CreateThingPolicyAttribute function.
        /// </summary>
        internal static string CreateThingPolicyEndLog {
            get {
                return ResourceManager.GetString("CreateThingPolicyEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of CreateThingPolicy function.
        /// </summary>
        internal static string CreateThingPolicyStartLog {
            get {
                return ResourceManager.GetString("CreateThingPolicyStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of CreateThing function.
        /// </summary>
        internal static string CreateThingStartLog {
            get {
                return ResourceManager.GetString("CreateThingStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of CreateUserAttributeAttribute function.
        /// </summary>
        internal static string CreateUserAttributeEndLog {
            get {
                return ResourceManager.GetString("CreateUserAttributeEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of CreateUserAttribute function.
        /// </summary>
        internal static string CreateUserAttributeStartLog {
            get {
                return ResourceManager.GetString("CreateUserAttributeStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of CreateUserAttribute function.
        /// </summary>
        internal static string CreateUserEndLog {
            get {
                return ResourceManager.GetString("CreateUserEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of CreateUser function.
        /// </summary>
        internal static string CreateUserStartLog {
            get {
                return ResourceManager.GetString("CreateUserStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of DeleteThingAttribute function.
        /// </summary>
        internal static string DeleteThingAttributeEndLog {
            get {
                return ResourceManager.GetString("DeleteThingAttributeEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of DeleteThingAttribute function.
        /// </summary>
        internal static string DeleteThingAttributeStartLog {
            get {
                return ResourceManager.GetString("DeleteThingAttributeStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of DeleteThing function.
        /// </summary>
        internal static string DeleteThingEndLog {
            get {
                return ResourceManager.GetString("DeleteThingEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of DeleteThingPolicy function.
        /// </summary>
        internal static string DeleteThingPolicyEndLog {
            get {
                return ResourceManager.GetString("DeleteThingPolicyEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of DeleteThingPolicy function.
        /// </summary>
        internal static string DeleteThingPolicyStartLog {
            get {
                return ResourceManager.GetString("DeleteThingPolicyStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of DeleteThing function.
        /// </summary>
        internal static string DeleteThingStartLog {
            get {
                return ResourceManager.GetString("DeleteThingStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of DeleteUserAttribute function.
        /// </summary>
        internal static string DeleteUserAttributeEndLog {
            get {
                return ResourceManager.GetString("DeleteUserAttributeEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of DeleteUserAttribute function.
        /// </summary>
        internal static string DeleteUserAttributeStartLog {
            get {
                return ResourceManager.GetString("DeleteUserAttributeStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of DeleteUser function.
        /// </summary>
        internal static string DeleteUserEndLog {
            get {
                return ResourceManager.GetString("DeleteUserEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of DeleteUser function.
        /// </summary>
        internal static string DeleteUserStartLog {
            get {
                return ResourceManager.GetString("DeleteUserStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadThingAttribute function.
        /// </summary>
        internal static string ReadThingAttributeEndLog {
            get {
                return ResourceManager.GetString("ReadThingAttributeEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadThingAttributes function.
        /// </summary>
        internal static string ReadThingAttributesEndLog {
            get {
                return ResourceManager.GetString("ReadThingAttributesEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadThingAttributes function.
        /// </summary>
        internal static string ReadThingAttributesStartLog {
            get {
                return ResourceManager.GetString("ReadThingAttributesStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadThingAttribute function.
        /// </summary>
        internal static string ReadThingAttributeStartLog {
            get {
                return ResourceManager.GetString("ReadThingAttributeStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadThing function.
        /// </summary>
        internal static string ReadThingEndLog {
            get {
                return ResourceManager.GetString("ReadThingEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadThingPolicies function.
        /// </summary>
        internal static string ReadThingPoliciesEndLog {
            get {
                return ResourceManager.GetString("ReadThingPoliciesEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadThingPolicies function.
        /// </summary>
        internal static string ReadThingPoliciesStartLog {
            get {
                return ResourceManager.GetString("ReadThingPoliciesStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadThingPolicy function.
        /// </summary>
        internal static string ReadThingPolicyEndLog {
            get {
                return ResourceManager.GetString("ReadThingPolicyEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadThingPolicy function.
        /// </summary>
        internal static string ReadThingPolicyStartLog {
            get {
                return ResourceManager.GetString("ReadThingPolicyStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadThings function.
        /// </summary>
        internal static string ReadThingsEndLog {
            get {
                return ResourceManager.GetString("ReadThingsEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadThings function.
        /// </summary>
        internal static string ReadThingsStartLog {
            get {
                return ResourceManager.GetString("ReadThingsStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadThing function.
        /// </summary>
        internal static string ReadThingStartLog {
            get {
                return ResourceManager.GetString("ReadThingStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadUserAttribute function.
        /// </summary>
        internal static string ReadUserAttributeEndLog {
            get {
                return ResourceManager.GetString("ReadUserAttributeEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadUserAttributes function.
        /// </summary>
        internal static string ReadUserAttributesEndLog {
            get {
                return ResourceManager.GetString("ReadUserAttributesEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadUserAttributes function.
        /// </summary>
        internal static string ReadUserAttributesStartLog {
            get {
                return ResourceManager.GetString("ReadUserAttributesStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadUserAttribute function.
        /// </summary>
        internal static string ReadUserAttributeStartLog {
            get {
                return ResourceManager.GetString("ReadUserAttributeStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadUser function.
        /// </summary>
        internal static string ReadUserEndLog {
            get {
                return ResourceManager.GetString("ReadUserEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of ReadUsers function.
        /// </summary>
        internal static string ReadUsersEndLog {
            get {
                return ResourceManager.GetString("ReadUsersEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadUsers function.
        /// </summary>
        internal static string ReadUsersStartLog {
            get {
                return ResourceManager.GetString("ReadUsersStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of ReadUser function.
        /// </summary>
        internal static string ReadUserStartLog {
            get {
                return ResourceManager.GetString("ReadUserStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of UpdateThingAttribute function.
        /// </summary>
        internal static string UpdateThingAttributeEndLog {
            get {
                return ResourceManager.GetString("UpdateThingAttributeEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of UpdateThingAttribute function.
        /// </summary>
        internal static string UpdateThingAttributeStartLog {
            get {
                return ResourceManager.GetString("UpdateThingAttributeStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of UpdateThing function.
        /// </summary>
        internal static string UpdateThingEndLog {
            get {
                return ResourceManager.GetString("UpdateThingEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of UpdateThingPolicy function.
        /// </summary>
        internal static string UpdateThingPolicyEndLog {
            get {
                return ResourceManager.GetString("UpdateThingPolicyEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of UpdateThingPolicy function.
        /// </summary>
        internal static string UpdateThingPolicyStartLog {
            get {
                return ResourceManager.GetString("UpdateThingPolicyStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of UpdateThing function.
        /// </summary>
        internal static string UpdateThingStartLog {
            get {
                return ResourceManager.GetString("UpdateThingStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of UpdateUserAttribute function.
        /// </summary>
        internal static string UpdateUserAttributeEndLog {
            get {
                return ResourceManager.GetString("UpdateUserAttributeEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of UpdateUserAttribute function.
        /// </summary>
        internal static string UpdateUserAttributeStartLog {
            get {
                return ResourceManager.GetString("UpdateUserAttributeStartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended execution of UpdateUser function.
        /// </summary>
        internal static string UpdateUserEndLog {
            get {
                return ResourceManager.GetString("UpdateUserEndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started execution of UpdateUser function.
        /// </summary>
        internal static string UpdateUserStartLog {
            get {
                return ResourceManager.GetString("UpdateUserStartLog", resourceCulture);
            }
        }
    }
}
