name: Authorization Service PR  

on: [push]

env:
  buildConfiguration: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build ./ApiExampleProject/ApiExampleProject.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./ApiExampleProject/ApiExampleProject.sln --filter Category!=Integration --configuration Release

  sonarCloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.1
        with:
          projectKey: jwendl-authorization-service-example
          projectBaseDir: ./ApiExampleProject
        env:
          SONAR_TOKEN: ${{ secrets.SonarToken }} 

  secretScan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Secret Scan
        uses: max/secret-scan@1.0.0
