name: Authorization Service PR  

on:
  pull_request:
    branches:
      - master

env:
  buildConfiguration: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Build with dotnet
        run: dotnet build ./src/ApiExampleProject.sln --configuration $buildConfiguration

      - name: Test with dotnet
        run: dotnet test ./src/ApiExampleProject.sln --filter Category!=Integration --configuration $buildConfiguration

  credScan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: gitCret
        uses: CySeq/gitcret@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validateTerraformPlan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'deployment/cloud'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_SUBSCRIPTION_ID: 959965bb-d9df-4c6f-825e-37e1090d817d
          ARM_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'deployment/cloud'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_SUBSCRIPTION_ID: 959965bb-d9df-4c6f-825e-37e1090d817d
          ARM_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: 'deployment/cloud'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_SUBSCRIPTION_ID: 959965bb-d9df-4c6f-825e-37e1090d817d
          ARM_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'deployment/cloud'
          tf_actions_comment: true
          args: '-out=plan.tfplan'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_SUBSCRIPTION_ID: 959965bb-d9df-4c6f-825e-37e1090d817d
          ARM_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          TF_VAR_dashboard_resource_group_name: Dashboard
          TF_VAR_dashboard_name: jwdashboard
          TF_VAR_dashboard_location: westus2
          TF_VAR_app_client_secret_key_vault_uri: "https://jwappkeyvault.vault.azure.net/secrets/app-client-secret/"
          TF_VAR_policy_manager_resource_group_name: PolicyManager
          TF_VAR_policy_manager_location: westus2
          TF_VAR_policy_manager_storage_account_name: jwpolicymanagerstorage
          TF_VAR_policy_manager_functions_plan_name: jwpolicymanagerplan
          TF_VAR_policy_manager_functions_name: jwpolicymanagerapi
          TF_VAR_policy_manager_app_insights_name: jwpolicymanagerai
          TF_VAR_policy_manager_sql_server_name: jwpolicymanagerdb
          TF_VAR_policy_manager_sql_database_name: PolicyManager
          TF_VAR_policy_manager_sql_tenant_id: 72f988bf-86f1-41af-91ab-2d7cd011db47
          TF_VAR_policy_manager_sql_object_id: 2609bcf7-475f-49c0-8040-85e667b4f3aa
          TF_VAR_customer_data_resource_group_name: CustomerData
          TF_VAR_customer_data_location: westus2
          TF_VAR_customer_data_storage_account_name: jwcustomerdatastorage
          TF_VAR_customer_data_functions_plan_name: jwcustomerdataplan
          TF_VAR_customer_data_functions_name: jwcustomerdataapi
          TF_VAR_customer_data_app_insights_name: jwcustomerdataai
          TF_VAR_customer_data_sql_server_name: jwcustomerdatadb
          TF_VAR_customer_data_sql_database_name: CustomerData
          TF_VAR_customer_data_sql_tenant_id: 72f988bf-86f1-41af-91ab-2d7cd011db47
          TF_VAR_customer_data_sql_object_id: 2609bcf7-475f-49c0-8040-85e667b4f3aa

  automate-pullrequest-review:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PRs by Justin
        if: github.actor == 'juswen@microsoft.com'
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: APPROVE
          body: 'Thank you Justin 🙏'
