name: Authorization Service PR  

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master

env:
  buildConfiguration: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release ApiExampleProject/ApiExampleProject.sln
    - name: Test with dotnet
      run: dotnet test ./src/Solution.sln --configuration Release
